apiVersion: v1
kind: Secret
metadata:
  name: vuln-scanner-secrets
  namespace: vuln-scanner
type: Opaque
data:
  jwt-secret: ${BASE64_ENCODED_JWT_SECRET}  # Replace with actual base64 encoded secret
