apiVersion: v1
kind: ServiceAccount
metadata:
  name: vulnerability-scanner-sa
  namespace: k8s-vulnerability-scanner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vulnerability-scanner-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vulnerability-scanner-binding
subjects:
- kind: ServiceAccount
  name: vulnerability-scanner-sa
  namespace: k8s-vulnerability-scanner
roleRef:
  kind: ClusterRole
  name: vulnerability-scanner-role
  apiGroup: rbac.authorization.k8s.io
