apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: vuln-scanner
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: vuln-scanner-sa
      containers:
      - name: backend
        image: your-registry/k8s-vuln-scanner-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: scanner-secrets
              key: JWT_SECRET_KEY
        - name: DB_URI
          valueFrom:
            secretKeyRef:
              name: scanner-secrets
              key: DB_URI
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vuln-scanner-sa
  namespace: vuln-scanner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vuln-scanner-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vuln-scanner-binding
subjects:
- kind: ServiceAccount
  name: vuln-scanner-sa
  namespace: vuln-scanner
roleRef:
  kind: ClusterRole
  name: vuln-scanner-role
  apiGroup: rbac.authorization.k8s.io
